# Generated by Django 2.2.6 on 2019-10-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20191010_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alt_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
