# Generated by Django 2.2.6 on 2019-10-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('readCategories', models.CharField(max_length=100)),
                ('writeCategories', models.CharField(max_length=100)),
                ('acceptMembers', models.BooleanField()),
                ('modifyRoles', models.BooleanField()),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
